package com.mabahmani.domain.vo.enum

enum class NameGroup {
    OSCAR_BEST_ACTRESS_NOMINEES,
    OSCAR_BEST_ACTOR_NOMINEES,
    OSCAR_BEST_ACTRESS_WINNERS,
    OSCAR_BEST_ACTOR_WINNERS,
    OSCAR_BEST_SUPPORTING_ACTRESS_NOMINEES,
    OSCAR_BEST_SUPPORTING_ACTOR_NOMINEES,
    OSCAR_BEST_SUPPORTING_ACTRESS_WINNERS,
    OSCAR_BEST_SUPPORTING_ACTOR_WINNERS,
    OSCAR_BEST_DIRECTOR_NOMINEES,
    BEST_DIRECTOR_WINNER,
    OSCAR_WINNER,
    OSCAR_NOMINEE
}