package com.mabahmani.domain.vo.enum

enum class TitleGroup {
    TOP_100,
    TOP_250,
    TOP_1000,
    BOTTOM_100,
    BOTTOM_250,
    BOTTOM_1000,
    OSCAR_WINNER,
    EMMY_WINNER,
    GOLDEN_GLOBE_WINNER,
    OSCAR_NOMINEE,
    EMMY_NOMINEE,
    GOLDEN_GLOBE_NOMINEE,
    BEST_PICTURE_WINNER,
    BEST_DIRECTOR_WINNER,
    OSCAR_BEST_PICTURE_NOMINEES,
    OSCAR_BEST_DIRECTOR_NOMINEES,
    NATIONAL_FILM_PRESERVATION_BOARD_WINNER,
    RAZZIE_WINNER,
    RAZZIE_NOMINEE
}