package com.mabahmani.domain.vo.enum

enum class TitleSort {
    MOVIEMETER_ACS,
    MOVIEMETER_DESC,
    ALPHA_ASC,
    ALPHA_DESC,
    USER_RATING_ASC,
    USER_RATING_DESC,
    NUM_VOTES_ASC,
    NUM_VOTES_DESC,
    BOXOFFICE_GROSS_US_ASC,
    BOXOFFICE_GROSS_US_DESC,
    RUNTIME_ASC,
    RUNTIME_DESC,
    YEAR_ASC,
    YEAR_DESC,
    RELEASE_DATE_ASC,
    RELEASE_DATE_DESC
}